DROP TABLE IF EXISTS bookings CASCADE;

DROP TABLE IF EXISTS slots CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;

DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS test_messages CASCADE;


DROP EXTENSION IF EXISTS "uuid-ossp";